<?php
$z[0]=Array("global","\r\n                    \$a=\"\r\n                    <li class='col-4-1 not-animated last' data-animate='fadeInUp' >\";\r\n                      \$b=\"\r\n                    \r\n                    <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                      if ((@me%4)==0 && @me!=12)  @me=\$a;\r\n                      else  @me=\$b;\r\n                      ",0,421);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",535,550);
$z[2]=Array("picname","",562,578);
$z[3]=Array("arcurl","",694,709);
$z[4]=Array("title","",727,741);
$z[5]=Array("description","",926,976);
$z[5][4]['function']="cn_substr(@me,180)";

?>