<?php
$z[0]=Array("field","",115,134);
$z[0][4]['name']="title";
$z[1]=Array("global","",135,161);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",202,224);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",264,315);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2387,2422);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2700,2734);
$z[5][4]['filename']="top.htm";
$z[6]=Array("field","",3314,3333);
$z[6][4]['name']="title";
$z[7]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a> ",3446,3522);
$z[8]=Array("field","",3575,3627);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("field","",3837,3855);
$z[9][4]['name']="body";
$z[10]=Array("type","\r\n                      <div class=\"float-right detail-bottom-button\"><a href=\"[field:typeurl/]\">查看更多</a></div>\r\n                      ",3940,4106);
$z[11]=Array("include","",5556,5593);
$z[11][4]['filename']="footer.htm";

?>