<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:jiage itemname="价格" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jiage>
<field:jianjie itemname="简介" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:jianjie>
