<?php
$z[0]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",1417,1631);
$z[0][4]['typeid']="1";
$z[0][4]['reid']="1";
$z[0][4]['type']="son";
$z[1]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",2805,3019);
$z[1][4]['typeid']="9";
$z[1][4]['reid']="9";
$z[1][4]['type']="son";
$z[2]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",4193,4407);
$z[2][4]['typeid']="5";
$z[2][4]['reid']="5";
$z[2][4]['type']="son";
$z[3]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",5581,5795);
$z[3][4]['typeid']="3";
$z[3][4]['reid']="3";
$z[3][4]['type']="son";
$z[4]=Array("channel","\r\n                              <li><a href=\"[field:typelink/]\" target=\"_blank\"><span>[field:typename/]</span></a></li>\r\n                              ",6974,7188);
$z[4][4]['typeid']="7";
$z[4][4]['reid']="7";
$z[4][4]['type']="son";
$z[5]=Array("global","",9578,9604);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",9610,9634);
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",9685,9709);
$z[7][4]['name']="cfg_dizhi";
$z[8]=Array("global","",9826,9852);
$z[8][4]['name']="cfg_dianhua";

?>