<?php
$z[0]=Array("global","",1217,1243);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",1809,1835);
$z[1][4]['name']="cfg_dianhua";
$z[2]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",2293,2385);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channelartlist","\r\n            <li class=\"{dede:field.currentstyle/}\"><a class=\"first-level\" href=\"{dede:field name='typeurl'/}\" target=\"\"><strong >{dede:field name='typename'/}</strong></a><i></i>\r\n              <ul class=\"\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li class=\"\"><a class=\"\" href=\"[field:typelink/]\" target=\"\"><strong>[field:typename/]</strong></a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",2482,3034);
$z[3][4]['typeid']="top";
$z[3][4]['currentstyle']="current";
$z[4]=Array("global","",3369,3395);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channelartlist","\r\n          <li><a href=\"javascript:;\"><span>{dede:field name='typename'/}</span><i class=\"touch-arrow-down\"></i></a>\r\n            <ul>\r\n              {dede:channel type='son' noself='yes' }\r\n              <li><a href=\"[field:typelink/]\"><span>[field:typename/]</span></a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </li>\r\n          ",4126,4547);
$z[5][4]['typeid']="1,3,5,7,9,0";
$z[6]=Array("channelartlist","\r\n          <li><a href=\"{dede:field name='typeurl'/}\"><span>{dede:field name='typename'/}</span></a></li>\r\n          ",4559,4735);
$z[6][4]['typeid']="11,0";

?>