<?php
$z[0]=Array("global","",115,141);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",182,211);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",251,281);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",2495,2530);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",2808,2842);
$z[4][4]['filename']="top.htm";
$z[5]=Array("field","",3322,3350);
$z[5][4]['name']="content";
$z[6]=Array("include","",3592,3629);
$z[6][4]['filename']="footer.htm";

?>