<?php
$z[0]=Array("global","",115,141);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",182,211);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",251,281);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",2353,2388);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",4239,4268);
$z[4][4]['name']="position";
$z[5]=Array("type","\r\n            <h2>[field:typename /]</h2>\r\n            ",4375,4453);
$z[6]=Array("field","",4897,4925);
$z[6][4]['name']="content";
$z[7]=Array("include","",5107,5142);
$z[7][4]['filename']="left.htm";
$z[8]=Array("include","",5250,5287);
$z[8][4]['filename']="footer.htm";

?>