<?php
$z[0]=Array("field","",115,134);
$z[0][4]['name']="title";
$z[1]=Array("global","",135,161);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",202,231);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",271,329);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2401,2436);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",4287,4316);
$z[5][4]['name']="position";
$z[6]=Array("type","\r\n            <h2>[field:typename /]</h2>\r\n            ",4423,4501);
$z[7]=Array("list","\r\n                    <li><a href=\"javascript:;\" target=\"\"><img src=\"[field:picname/]\" height=\"74\" data-large-src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></li>\r\n                    ",5091,5301);
$z[8]=Array("include","",5552,5587);
$z[8][4]['filename']="left.htm";
$z[9]=Array("include","",5695,5732);
$z[9][4]['filename']="footer.htm";

?>