<?php
$z[0]=Array("field","",115,134);
$z[0][4]['name']="title";
$z[1]=Array("global","",135,161);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",202,231);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",271,329);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",2401,2436);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2714,2748);
$z[5][4]['filename']="top.htm";
$z[6]=Array("list","\r\n                  <div class=\"accordion-handle\">\r\n                    <h4>[field:title/]</h4>\r\n                    <i></i></div>\r\n                  <div class=\"accordion-pane\">\r\n                    <div class=\"qhd-content\"> [field:body/] </div>\r\n                  </div>\r\n                  ",3247,3594);
$z[6][4]['addfields']="body";
$z[6][4]['channelid']="1";
$z[7]=Array("include","",3856,3893);
$z[7][4]['filename']="footer.htm";

?>