<?php
$z[0]=Array("field","",270,299);
$z[0][4]['name']="position";
$z[1]=Array("field","",458,516);
$z[1][4]['name']="typeid";
$z[1][4]['function']="GetTopTypename(@me)";
$z[2]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\" class=\"\">[field:typename/]</a></li>\r\n        ",809,1034);
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";

?>